### ISSUE TITLE
Quality.

### ISSUE THREAD

**Issue by hasnogaems** [Lordmau5/node-spotify-downloader#46]
Is it download in max possible quality?

**Comment by Lordmau5** [comment]
Max quality is 160kbps because that's the maximum we can get through the Web player (since the API we rely on uses that).

Another way is not impossible, but very, **VERY**, difficult to implement and would include reverse engineering the whole desktop client.

**Comment by hasnogaems** [comment]
Thank you for such developed, clear and honest answer man.

**Comment by Lordmau5** [comment]
On a side-note:
We were looking into a way to get 320kbps or even higher quality (because better quality is always nice, eh? ;))
But we couldn't figure out a way, that's the issue.

Spotify wanted to bring 320kbps streams to the web player for a long time already, but they still haven't, so there's that...
